[package]
name = "ah-release-tool"
version = "2.0.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
ah-release-manifest = { path = "../ah-release-manifest" }
base64.workspace = true
clap.workspace = true
ed25519-dalek.workspace = true
semver.workspace = true
sha2.workspace = true
tempfile.workspace = true
thiserror.workspace = true
zeroize = "1"
zip.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
serde_yaml.workspace = true
